version: "3.9"

services:

  # Add our proxy route to nginx
  proxy:
    volumes:
      - ./services/snatchbot/support/snatchbot.subfolder.conf:/config/nginx/proxy-confs/snatchbot.subfolder.conf

  snatchbot:
    extends:
      file: ./services/snatchbot/docker-compose.yml
      service: snatchbot
    build:
      context: ./services/snatchbot
    volumes:
      - ./services/snatchbot:/code/snatchbot
