version: '3.9'

services:
  snatchbot:
    build:
      context: .
    ports:
      - 8080
    restart: unless-stopped
    volumes:
      - .:/code/snatchbot
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-*info*,*warn*,*error*}
      - domain
      - token
